services:
  - type: web
    name: telegram-approval-cloud
    env: node
    plan: free
    buildCommand: npm install && cd src/webapp && npm install
    startCommand: cd src/webapp && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: LOG_LEVEL
        value: info
